export const CursosItems = [
    {
        cursoFilter: "UX-writing",
        imageLink: "src/assets/img/cursos/1mio.webp",
        imageAlt: "1mio",
        postTitle: "1mio",
        postContent: "A iniciativa Um Milhão de Oportunidades (1MiO) é a maior articulação do Brasil pela inclusão produtiva de adolescentes e jovens no mundo do trabalho. no site tem diversos cursos, eventos e oportunidades de trabalho divulgadas!",
        postLink: "https://1mio.com.br/feeds",
    },
    {
        cursoFilter: "desenvolvimento",
        imageLink: "src/assets/img/cursos/adobeeduca.webp",
        imageAlt: "adobe educa",
        postTitle: "Adobe Educa",
        postContent: "A Adobe Educa é a plataforma de educação gratuita para todos os professores do Brasil! aqui você encontra cursos com especialistas em todos os programas da Adobe Creative Cloud: design, ilustração, animação, produção de vídeo, editoração e muito mais",
        postLink: "https://por.adobe-educa.com",
    },
    {
        cursoFilter: "UX-writing",
        imageLink: "src/assets/img/cursos/avamec.webp",
        imageAlt: "AVAMEC",
        postTitle: "AVAMEC",
        postContent: "A AVAMEC é um ambiente virtual colaborativo de aprendizagem que a concepção, administração e desenvolvimento de diversos tipos de ações formativas, como cursos a distância, complemento a cursos presenciais, projetos pesquisa, projetos colaborativos e diversas outras formas de apoio educacional distância ao processo ensino-aprendizagem!",
        postLink: "https://avamec.mec.gov.br/#/",
    },
    {
        cursoFilter: "active",
        imageLink: "src/assets/img/cursos/amazonalexa.webp",
        imageAlt: "Alexa Skills: Design de Voz",
        postTitle: "Alexa Skills: Design de Voz",
        postContent: "Aprenda as melhores práticas de design para skills da Alexa, você aprenderá a criar experiências de voz naturais e enriquecedoras.",
        postLink: "https://build.amazonalexadev.com/cursoalexa-designdevoz.html",
    },
    {
        cursoFilter: "UX-design filter-desenvolvimento",
        imageLink: "src/assets/img/cursos/awari.webp",
        imageAlt: "Cursos Introdutórios na Awari",
        postTitle: "Cursos Introdutórios na Awari",
        postContent: "A Awari oferece cursos gratuitos em Data Science Programação, UX/UI design e outros Para acessá-los, basta você clicar rolar até a seção de 'Cursos em destaque'!",
        postLink: "https://awari.com.br/#categorias",
    },
    {
        cursoFilter: "cloud",
        imageLink: "src/assets/img/cursos/awsskillbuilder.webp",
        imageAlt: "AWS Skill Builder",
        postTitle: "AWS Skill Builder",
        postContent: "A Amazon criou o AWS Skill Builder, que é o seu centro de aprendizado para o desenvolvimento das habilidades de nuvem mais desejadas! A plataforma tem vários cursos sobre a cloud AWS",
        postLink: "https://explore.skillbuilder.aws/learn",
    },
]